### ISSUE TITLE
Feature: Share todo completion rate

### ISSUE THREAD

**Issue by jschuur** [jschuur/coworking.party#102]
Building on the new todo list feature from #2:

- [x] update schema (use DB migrations per #85) 
- [x] share completion rate, task count changes with room
- [x] show progress bar on user list entry (radial [progress circle](https://tigrr.github.io/circle-progress/examples.html), [Tailwind gist](https://gist.github.com/eYinka/873be69fae3ef27b103681b8a9f5e379)?)
- [x] master progress for room

**Comment by jschuur** [comment]
Done in c40a62f8f4837a3cb0c59df0eec532c63b53fb17
