### ISSUE TITLE
Feature: Log session duration

### ISSUE THREAD

**Issue by jschuur** [jschuur/coworking.party#11]
Store the start/end of a user's session

Design should consider that (i.e. at least always update the latest session

- [ ] create schema/DB table
- [ ] create new session on fresh connect with no current connections
- [ ] store current session in (private) user data
- [ ] record session end date on full user disconnect
- [ ] update the session end whenever any user data changes too, just in case we miss a disconnect
- [ ] what do we do if a new session is create and he last one doesn't have an end time?
- [ ] attach tagline to session, if #8 is already implemented
- [ ] attached mood to session, if # is already implemented

This task just handles tracking sessions. How this information is used/visualised is handled elsewhere.
