### ISSUE TITLE
Feature: Log tagline update meta data

### ISSUE THREAD

**Issue by jschuur** [jschuur/coworking.party#12]
Log when a user updates their status, but until further discussion/feedback, don't log the actual status text.

- [ ] log which userId performed a status update
- [ ] add session ID (#11) if available
- [ ] add room name
- [ ] add tagline length
- [ ] add mood (#8 ) while making update if available

Information to be used in a later feature.
